services:
#  db:
#    image: postgres:13.3-alpine3.14
#    container_name: formulaone-db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=formulaone
#    ports:
#      - 5432:5432
#
#    volumes:
#      - ./data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./csv:/var/lib/csv
  app:
    build: .
    ports:
      - "3000:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

